version: '3.5'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      PG_HOST: pg
    volumes:
    - ./serp:/app
    ports:
      - 8000:8000
#    command: python manage.py runserver 0.0.0.0:5000
#    command: python manage.py migrate
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py runserver 0.0.0.0:8000 && python3 manage.py work"
#    command: sh -c "python3 manage.py migrate --noinput"
    depends_on:
      - pg

  pg:
    image: postgres:12
    environment:
      POSTGRES_DB: serpdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5435:5432"
