# Generated by Django 3.1.3 on 2020-11-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(null=True)),
                ('is_poison', models.BooleanField(default=True)),
                ('food', models.TextField(null=True)),
            ],
        ),
    ]
